/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kasus;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test 
    public void testAssert() {
        Bicycle classUnderTest = new Bicycle();
        assertNotNull("app should have a greeting", classUnderTest);
    }
}
